In [5]:
import numpy as np
from finitediff import get_weights
get_weights

<cyfunction get_weights at 0x1051272b0>

In [14]:
N = 3
pts = []
for n in np.arange(N):
    if n == 0:  pts.append(0.0)
    else:
        pts.append(n)
        pts.append(-n)
    
pts = np.array(pts)
c = get_weights(pts, 0., maxorder=2*(N-1))
print("Coefficients for %dth order filter" % (2*(N-1)))
print(c.transpose()[-1])
    

Coefficients for 4th order filter
[ 6. -4. -4.  1.  1.]


In [11]:
N = 4
pts = []
for n in np.arange(N):
    if n == 0:  pts.append(0.0)
    else:
        pts.append(n)
        pts.append(-n)
    
pts = np.array(pts)
c = get_weights(pts, 0., maxorder=2*(N-1))
print("Coefficients for %dth order filter" % (2*(N-1)))
print(c.transpose()[-1])

Coefficients for 6th order filter
[-20.  15.  15.  -6.  -6.   1.   1.]


In [12]:
N = 5
pts = []
for n in np.arange(N):
    if n == 0:  pts.append(0.0)
    else:
        pts.append(n)
        pts.append(-n)
    
pts = np.array(pts)
c = get_weights(pts, 0., maxorder=2*(N-1))
print("Coefficients for %dth order filter" % (2*(N-1)))
print(c.transpose()[-1])

Coefficients for 8th order filter
[ 70. -56. -56.  28.  28.  -8.  -8.   1.   1.]


In [13]:
N = 6
pts = []
for n in np.arange(N):
    if n == 0:  pts.append(0.0)
    else:
        pts.append(n)
        pts.append(-n)
    
pts = np.array(pts)
c = get_weights(pts, 0., maxorder=2*(N-1))
print("Coefficients for %dth order filter" % (2*(N-1)))
print(c.transpose()[-1])

Coefficients for 10th order filter
[-252.  210.  210. -120. -120.   45.   45.  -10.  -10.    1.    1.]
